from flask import Flask,render_template
from flask_mail import Mail,Message
from requests import get
import urllib.request, json
import requests
import schedule
import time
import mysql.connector

app = Flask(__name__)
app.secret_key = "1509"

mail=Mail(app)

UPLOAD_FOLDER = '/uploads/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAIL_SERVER']='smtp.gmail.com'
app.config['MAIL_PORT'] = 465
app.config['MAIL_USERNAME'] = 'noreply.valuemart@gmail.com'
app.config['MAIL_PASSWORD'] = 'valuemart123'
app.config['MAIL_USE_TLS'] = False
app.config['MAIL_USE_SSL'] = True

mail = Mail(app)


email_list = []

def test1():
    try : 
        cnx = mysql.connector.connect(host='localhost',user='root',passwd='',database='cron_test')
        con = cnx.cursor()
    except :
        print('Connection Error')
        pass
    try :
        sql = "SELECT * FROM test WHERE isSend='NO'"
        con.execute(sql)
        temp = con.fetchall()
        for i in temp :
            if i[1] not in email_list :
                email_list.append(i[1])
        print('Emails : ',email_list)       
    except :
        print('Error In Fetching...') 
    print('Cron 1 Started Executing....')
    # print('Email List : ',email_list)
    try :
        if len(email_list) != 0 :
            for i in range(len(email_list)):
                if len(str(email_list[i]).strip()) != 0 :
                    email = str(email_list[i])
                    msg = Message('VERIFY YOUR EMAIL', sender = 'VALUEMART', recipients = [email])
                    msg.html = '''<!DOCTYPE html>
                                                                <html lang="en">
                                                                <head>
                                                                    <meta charset="UTF-8">
                                                                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                    <meta http-equiv="X-UA-Compatible" content="ie=edge">
                                                                    <title>Document</title>
                                                                </head>
                                                                <body>
                                                                    <h2>Hey !</h2>
                                                                          This Message Is Generated By Cron Job.  
                                                                </body>
                                                                </html>'''
                    mail.send(msg)
                    print('Mail Sent To',email)
                    try :
                        sql = "UPDATE test SET isSend='YES' WHERE email='%s'" % (email_list[i])
                        con.execute(sql)
                        cnx.commit()
                    except :
                        print('Error In Updating Record In Database...')
                    del email_list[i]
                else :
                    print('Not Valid Email...')
                    continue
        else :
            print('Email List is Empty...')
    except :
        print('Error In Sending Mail...')
    print('Cron 1 Executed....\n')
    cnx.close()
def test2():
    print('test2')
    

@app.route('/',methods=['GET','POST'])
def ind():
    schedule.every(10).seconds.do(test1)
    while True :
        schedule.run_pending()
        time.sleep(1)
        
if __name__ == "__main__" :
    app.run(host="127.0.0.1",port=5001,debug=True)